# Generated by Django 5.0.6 on 2024-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_poblshd',
            field=models.BooleanField(default=True),
        ),
    ]
